redhat_sensei/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'redhat_sensei.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^account/', include('registration.backends.default.urls')),
    url(r'^$', 'redhat_sensei_quiz.views.index', name='index'),
#    url(r'^results/', 'redhat_sensei_quiz.views.results', name='results'),
#    url(r'^account_administration/', 'redhat_sensei_quiz.views.account_administration', name='account_administration'),
    url(r'^quiz_selection/', 'redhat_sensei_quiz.views.quiz_selection', name='quiz_selection'),
#    url(r'^quiz_selection/', include('redhat_sensei_quiz.urls', namespace="redhat_sensei_quiz")),
    url(r'^quiz/', include('redhat_sensei_quiz.urls', namespace="redhat_sensei_quiz")),
    url(r'^quiz/', 'redhat_sensei_quiz.views.git_quiz', name='git_quiz'),
    url(r'^resources/', 'redhat_sensei_quiz.views.resources', name='resources'),
    url(r'^admin/', include(admin.site.urls)),



#    url(r'^results/', 'giturdone_quiz.views.results', name='results'),
# Left line below in prod version for now just in case it is needed
#    url(r'^quiz/', 'giturdone_quiz.views.git_quiz', name='git_quiz'),
#    url(r'^account/', include('registration.backends.default.urls')),
#    url(r'^admin/', include(admin.site.urls)),
]

redhat_sensei_quiz/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # ex: /quiz/
    url(r'^quiz_selection/', views.quiz_selection, name='quiz_selection'),
    url(r'^$', views.git_quiz, name='index'),
    url(r'^resources/', views.resources, name='resources'),
    # ex: /quiz/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /quiz/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /quiz/5/vote/
# Note: the answers url is not being used in the app but is left here
# as an example for future versions
#    url(r'^(?P<question_id>[0-9]+)/answer/$', views.answer, name='answer'),
]

redhat_sensei_quiz/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    category = models.CharField(max_length=30)

    def __unicode__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = models.CharField(max_length=200)
    answers = models.IntegerField(default=0)
    correct_answer = models.CharField(max_length=200, default='Linus Torvalds')


    def __unicode__(self):
        return self.answer_text

redhat_sensei_quiz/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from . models import Answer, Question
import random
import datetime
from django.utils.encoding import *
# The line below imports the user_response variable from the user_response.py file
from . user_response import user_response



# Create your views here.


# Note the index page used in the index function below tells the computer
# user about the application and what it is meant to be used for

def index(request):
    return render(request, 'index.html')

# quiz_selection page takes a user_response as input and displays associated quiz on Sensei Quiz page

def quiz_selection(request):
    if request.method == 'POST':
        user_response = request.POST.get('textfield', None)
        user_response = smart_text(user_response)
        f = open('redhat_sensei_quiz/user_response.py', 'w')
        # the line below write the text 'user_response = ' and concats the user_response the str function gets rid of u in front of string
        f.write('user_response = ' + repr(str(user_response)))
        f.close()
    return render(request, 'redhat_sensei_quiz/quiz_selection.html')


# git_quiz displays the quiz selected by user in the Sensei Quiz Selection page

def git_quiz(request):
    if user_response == 'None':
        return render(request, 'redhat_sensei_quiz/index.html')
    if user_response == '1':
        latest_question_list = Question.objects.filter(category="User Management")
    if user_response == '2':
        latest_question_list = Question.objects.filter(category="System Basics")
    if user_response == '3':
        latest_question_list = Question.objects.filter(category="Security & Identity")
    if user_response == '4':
        latest_question_list = Question.objects.filter(category="Basic Configuration")
    if user_response == '5':
        latest_question_list = Question.objects.filter(category="Jobs & Services")
    if user_response == '6':
        latest_question_list = Question.objects.filter(category="Kernel, Boot, & Hardware")
    if user_response == '7':
        latest_question_list = Question.objects.filter(category="Software Management")
    if user_response == '8':
        latest_question_list = Question.objects.filter(category="Filesystem, Volumes, & Disks")
    if user_response == '9':
        latest_question_list = Question.objects.filter(category="Networking")
    if user_response == '10':
        latest_question_list = Question.objects.filter(category="Resource Management")
    if user_response == '11':
        latest_question_list = Question.objects.filter(category="UNIX Commands")
    context = {'user_response': user_response, 'latest_question_list': latest_question_list}
    return render(request, 'redhat_sensei_quiz/index.html', context)


# detail view displays the quiz questions

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'redhat_sensei_quiz/detail.html', {'question': question})

# results pages displays whether answer given by user was correct and also displays the correct answer

def results(request, question_id):
    latest_question_list = Question.objects.order_by('?')
    if request.method == 'POST':
        question = get_object_or_404(Question, pk=question_id)
        user_answer = request.POST.get('textfield', None)
        # Get the question object
        q = Question.objects.get(pk=question_id)
        # Get all the answers associated with the question object
        a = q.answer_set.all()
        # Get the first element in the list of answers
        value = a[0]
        # smart_text is a django utility that converts an object to a unicode string
        correct_answer = smart_text(value)
        context = {'latest_question_list': latest_question_list, 'answer': user_answer, 'question': question, 'correct_answer': correct_answer}
    return render(request, 'redhat_sensei_quiz/results.html', context)


# resources pages contains videos and websites related to the subject matter

def resources(request):
    return render(request, 'redhat_sensei_quiz/resources.html')

redhat_sensei_quiz/templates/giturdone_quiz/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Git Quiz</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<style>
a:link {
    color: black;
    background-color: transparent;
    text-decoration: none;
}
a:visited {
    color: blue;
    background-color: transparent;
    text-decoration: none;
}
a:hover {
    color: red;
    background-color: transparent;
    text-decoration: underline;
}
a:active {
    color: purple;
    background-color: transparent;
    text-decoration: underline;
}
</style>

</head>
<body>
<div class="w3-container w3-red">
{% if request.user.is_authenticated %}
  <h1>Welcome {% if request.user.first_name %}
      {{ request.user.first.name }}
      {% else %}
      {{ request.user.username }}
      {% endif %}
      - To Git Ur Done<br>
      <img src="/static/images/git.png" style="width:50px;height:50px;">
  </h1>
{% else %}
<h1> Welcome To Git Ur Done</h1> <img src="/static/images/git.png" style="width:50px;height:50px;">
{% endif %}
</div>



<div class="w3-container w3-yellow">
<img src="/static/images/dj.png" style="width:25" align="right">
<br>
{% if request.user.is_authenticated %}
<h3>
<a href="http://localhost:8000/" target="_blank">About</a>   <a href="http://localhost:8000/quiz/" target="_blank">Quiz</a>  <a href="http://localhost:8000/quiz/resources/" target="_blank">Resources</a>  <a href="http://localhost:8000/account/logout" target="_blank">Logout</a>
</h3>
{% else %}
<h3>
<a href="http://localhost:8000/" target="_blank">About</a>   <a href="http://localhost:8000/account/register" target="_blank">Register</a>    <a href="http://localhost:8000/account/login/"target="_blank" >Login</a>
</h3>
{% endif %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<center>
Click On A Question Below
<br>
<br>
<br>
<br>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'giturdone_quiz:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</center>
</p>
</div>
<div class="w3-container w3-blue">
  <h5>

  </h5>
  <p><center>Web Design & Application Development By - <a href="http://facebook.com/gil.rael.37/" target="_blank">Gil Rael</a><br>
Software Developed By A Nerd For Nerds</center></p>
</div>
</head>
</body>
</html>

redhat_sensei_quiz/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Red Hat Linux Sensei</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link rel="stylesheet" href="/static/css/style.css" type="text/css" charset="utf-8" />
</head>
<body>
<div id="wrapper">
  <div id="header">
    <h1><span>RED HAT LINUX SENSEI</span></h1>
  </div>
  <div id="nav">
       {% if request.user.is_authenticated %}
    <ul>
      <li class="first"><a href="http://localhost:8000/"><em>A</em>BOUT</a></li>
      <li><a href="http://localhost:8000/quiz_selection/"><em>S</em>ENSEI <em>Q</em>UIZ <em>S</em>ELECTION</a></li>
      <li><a href="http://localhost:8000/quiz/"><em>S</em>ENSEI <em>Q</em>UIZ</a></li>
      <li><a href="http://localhost:8000/resources/"><em>R</em>ESOURCES</em></a></li>
      <li><a href="http://localhost:8000/account/logout/"><em>L</em>OGOUT</a></li>
       {% else %}
      <li class="first"><a href="http://localhost:8000/"><em>A</em>BOUT</a></li>
      <li><a href="http://localhost:8000/account/register/"><em>R</em>EGISTER</a></li>
      <li><a href="http://localhost:8000/account/login/"><em>L</em>OGIN</a></li>
       {% endif %}
    </ul>
  </div>
  <div id="body">
    <div id="content">
      <div class="i">
          {% if request.user.is_authenticated %}
        <h2><strong>Welcome {% if request.user.first_name %}</strong> To Red Hat Linux Sensei</h2>
              {{ request.user.first.name }}
              {% else %}
              {{ request.user.username }}
          {% endif %}
          {% else %}
          <h2><strong>Welcome </strong> To Red Hat Linux Sensei</h2>
          {% endif %}
        <p>Red Hat Linux Sensei is an educational web application designed to test and improve Red Hat Linux system administration skills.
        The application is designed and developed by Gil Rael using the Python Django web framework.</p>
        <br>
        <br>
        <br>
        </div>
      </div>
    </div>
    <div id="copyright"> &copy;  Copyright 2016 | Web Design & Software Application Development By <a target=_blank href="http://www.gilrael.com">Gil Rael</a></div>
  </div>
  <div id="footer"> </div>
</div>
</body>
</html>

redhat_sensei_quiz/templates/redhat_sensei_quiz/backup/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Git Quiz Detail</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<style>
a:link {
    color: black;
    background-color: transparent;
    text-decoration: none;
}
a:visited {
    color: blue;
    background-color: transparent;
    text-decoration: none;
}
a:hover {
    color: red;
    background-color: transparent;
    text-decoration: underline;
}
a:active {
    color: purple;
    background-color: transparent;
    text-decoration: underline;
}
</style>

</head>
<body>

<div class="w3-container w3-red">
{% if request.user.is_authenticated %}
  <h1>Welcome {% if request.user.first_name %}
      {{ request.user.first.name }}
      {% else %}
      {{ request.user.username }}
      {% endif %}
      - To Git Ur Done<br>
      <img src="/static/images/git.png" style="width:50px;height:50px;">
  </h1>
{% else %}
<h1> Welcome To Git Ur Done</h1> <img src="/static/images/git.png" style="width:50px;height:50px;">
{% endif %}
</div>



<div class="w3-container w3-yellow">
<img src="/static/images/dj.png" style="width:25" align="right">
<br>
{% if request.user.is_authenticated %}
<h3>
<a href="http://localhost:8000/" target="_blank">About</a>   <a href="http://localhost:8000/quiz/" target="_blank">Quiz</a>  <a href="http://localhost:8000/quiz/resources/" target="_blank">Resources</a>  <a href="http://localhost:8000/account/logout" target="_blank">Logout</a>
</h3>
{% else %}
<h3>
<a href="http://localhost:8000/" target="_blank">About</a>   <a href="http://localhost:8000/account/register" target="_blank">Register</a>    <a href="http://localhost:8000/account/login/"target="_blank" >Login</a>
</h3>
{% endif %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<center>
<h2>{{ question.question_text }}</h2>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'redhat_sensei_quiz:results' question.id %}" method="post">
{% csrf_token %}
  <table>{{ form.as_table }}</table>
   <p><label for="id_name"> Type Your Answer:</label>
<input class="textinput textInput form-control" id="id_name" maxlength="100" name="textfield" type="text" /></p>
  <input type="submit" value="Submit" />
</form>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</center>
</p>
</div>
<div class="w3-container w3-blue">
  <h5>

  </h5>
  <p><center>Web Design & Application Development By - <a href="http://facebook.com/gil.rael.37/" target="_blank">Gil Rael</a><br>
Software Developed By A Nerd For Nerds</center></p>
</div>
</head>
</body>
</html>

redhat_sensei_quiz/templates/redhat_sensei_quiz/backup/quiz_selection.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Red Hat Linux Sensei Quiz</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link rel="stylesheet" href="/static/css/style.css" type="text/css" charset="utf-8" />
</head>
<body>
<div id="wrapper">
  <div id="header">
    <h1><span>RED HAT LINUX SENSEI</span></h1>
  </div>
  <div id="nav">
      {% if request.user.is_authenticated %}
    <ul>
      <li class="first"><a href="http://localhost:8000/"><em>A</em>BOUT</a></li>
      <li><a href="http://localhost:8000/quiz/"><em>S</em>ENSEI <em>Q</em>UIZ</a></li>
      <li><a href="http://localhost:8000/account/logout/"><em>L</em>OGOUT</a></li>
       {% else %}
      <li class="first"><a href="http://localhost:8000/"><em>A</em>BOUT</a></li>
      <li><a href="http://localhost:8000/account/register/"><em>R</em>EGISTER</a></li>
      <li><a href="http://localhost:8000/account/login/"><em>L</em>OGIN</a></li>
       {% endif %}

    </ul>
  </div>
  <div id="body">
    <div id="content">
      <div class="i">
          {% if request.user.is_authenticated %}
        <h2><strong>Welcome {% if request.user.first_name %}</strong> To Red Hat Linux Sensei</h2>
                {{ request.user.first.name }}
                {% else %}
                {{ request.user.username }}
                {% endif %}
          {% else %}
          <h2><strong>Welcome </strong> To Red Hat Linux Sensei</h2>
          {% endif %}

  <!--      <p>Red Hat Linux Sensei is an educational web application designed to test and improve Red Hat Linux system administration skills.
        The application is designed and developed by Gil Rael using the Python Django web framework.</p>-->

        <h2><center><br></br><br></br>Coming Soon My Friends!</center></h2>
        </p>
        <br>
        <br>
        <br>
        <br>
<center><h2>Click On A Question Below</h2></center>
<br>
<br>
<br>
<br>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'redhat_sensei_quiz:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Questions are available.</p>
{% endif %}


        </div>
      </div>
    </div>
    <div id="copyright"> &copy; Copyright 2016 | Web Design & Software Application Development By <a target=_blank href="http://www.gilrael.com">Gil Rael</a></div>
  </div>
  <div id="footer"> </div>
</div>
</body>
</html>

redhat_sensei_quiz/templates/redhat_sensei_quiz/detail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Red Hat Linux Sensei Quiz</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link rel="stylesheet" href="/static/css/style.css" type="text/css" charset="utf-8" />
</head>
<body>
<div id="wrapper">
  <div id="header">
    <h1><span>RED HAT LINUX SENSEI</span></h1>
  </div>
  <div id="nav">
      {% if request.user.is_authenticated %}
    <ul>
      <li class="first"><a href="http://localhost:8000/"><em>A</em>BOUT</a></li>
      <li><a href="http://localhost:8000/quiz_selection/"><em>S</em>ENSEI <em>Q</em>UIZ <em>S</em>ELECTION</a></li>
      <li><a href="http://localhost:8000/quiz/"><em>S</em>ENSEI <em>Q</em>UIZ</a></li>
      <li><a href="http://localhost:8000/resources/"><em>R</em>ESOURCES</em></a></li>
      <li><a href="http://localhost:8000/account/logout/"><em>L</em>OGOUT</a></li>
       {% else %}
      <li class="first"><a href="http://localhost:8000/"><em>A</em>BOUT</a></li>
      <li><a href="http://localhost:8000/account/register/"><em>R</em>EGISTER</a></li>
      <li><a href="http://localhost:8000/account/login/"><em>L</em>OGIN</a></li>
       {% endif %}
     </ul>


  </div>
  <div id="body">
    <div id="content">
      <div class="i">
          {% if request.user.is_authenticated %}
        <h2><strong>Welcome {% if request.user.first_name %}</strong> To Red Hat Linux Sensei</h2>
                {{ request.user.first.name }}
                {% else %}
                {{ request.user.username }}
                {% endif %}
          {% else %}
          <h2><strong>Welcome </strong> To Red Hat Linux Sensei</h2>
          {% endif %}


<br>
<br>
<br>
<br>
<center>
<h2>{{ question.question_text }}</h2>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'redhat_sensei_quiz:results' question.id %}" method="post">
{% csrf_token %}
  <table>{{ form.as_table }}</table>
   <p><label for="id_name"> Type Your Answer:</label>
<input class="textinput textInput form-control" id="id_name" maxlength="100" name="textfield" type="text" /></p>
  <input type="submit" value="Submit" />
</form>
</center>
        </div>
      </div>
    </div>
    <div id="copyright"> &copy; Copyright 2016 | Web Design & Software Application Development By <a target=_blank href="http://www.gilrael.com">Gil Rael</a></div>
  </div>
  <div id="footer"> </div>
</div>
</body>
</html>

redhat_sensei_quiz/templates/redhat_sensei_quiz/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/html" xml:lang="en" lang="en">
<head>
<title>Red Hat Linux Sensei Quiz</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link rel="stylesheet" href="/static/css/style.css" type="text/css" charset="utf-8" />
</head>
<body>
<div id="wrapper">
  <div id="header">
    <h1><span>RED HAT LINUX SENSEI</span></h1>
  </div>
  <div id="nav">
      {% if request.user.is_authenticated %}
    <ul>
      <li class="first"><a href="http://localhost:8000/"><em>A</em>BOUT</a></li>
      <li><a href="http://localhost:8000/quiz_selection/"><em>S</em>ENSEI <em>Q</em>UIZ <em>S</em>ELECTION</a></li>
      <li><a href="http://localhost:8000/quiz/"><em>S</em>ENSEI <em>Q</em>UIZ</a></li>
      <li><a href="http://localhost:8000/resources/"><em>R</em>ESOURCES</em></a></li>
      <li><a href="http://localhost:8000/account/logout/"><em>L</em>OGOUT</a></li>
       {% else %}
      <li class="first"><a href="http://localhost:8000/"><em>A</em>BOUT</a></li>
      <li><a href="http://localhost:8000/account/register/"><em>R</em>EGISTER</a></li>
      <li><a href="http://localhost:8000/account/login/"><em>L</em>OGIN</a></li>
       {% endif %}

    </ul>
  </div>
  <div id="body">
    <div id="content">
      <div class="i">
          {% if request.user.is_authenticated %}
        <h2><strong>Welcome {% if request.user.first_name %}</strong> To Red Hat Linux Sensei</h2>
                {{ request.user.first.name }}
                {% else %}
                {{ request.user.username }}
                {% endif %}
          {% else %}
          <h2><strong>Welcome </strong> To Red Hat Linux Sensei</h2>
          {% endif %}

<!-- code below creates custom Red Hat Linux message based on user_response in Sensei Quiz Selection page-->

 {% if user_response = "1" %}
    <p><h2><center>Red Hat Linux User Management<br>Click On Question Below</center></h2></p>
 {% endif %}
 {% if user_response = "2" %}
    <p><h2><center>Red Hat Linux System Basics<br>Click On Question Below</center></h2></p>
 {% endif %}
 {% if user_response = "3" %}
    <p><h2><center>Red Hat Linux Security & Identity<br>Click On Question Below</center></h2></p>
 {% endif %}
 {% if user_response = "4" %}
    <p><h2><center>Red Hat Linux Basic Configuration<br>Click On Question Below</center></h2></p>
 {% endif %}
 {% if user_response = "5" %}
    <p><h2><center>Red Hat Linux Jobs & Services<br>Click On Question Below</center></h2></p>
 {% endif %}
 {% if user_response = "6" %}
    <p><h2><center>Red Hat Linux Kernel, Boot, & Hardware<br>Click On Question Below</center></h2></p>
 {% endif %}
 {% if user_response = "7" %}
    <p><h2><center>Red Hat Linux Software Management<br>Click On Question Below</center></h2></p>
 {% endif %}
 {% if user_response = "8" %}
    <p><h2><center>Red Hat Linux Filesystem, Volumes, & Disks<br>Click On Question Below</center></h2></p>
 {% endif %}
 {% if user_response = "9" %}
    <p><h2><center>Red Hat Linux Networking<br>Click On Question Below</center></h2></p>
 {% endif %}
 {% if user_response = "10" %}
    <p><h2><center>Red Hat Linux Resource Management<br>Click On Question Below</center></h2></p>
 {% endif %}
 {% if user_response = "11" %}
    <p><h2><center>Red Hat Linux UNIX Commands<br>Click On Question Below</center></h2></p>
 {% endif %}


 {% if request.user.is_authenticated %}
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'redhat_sensei_quiz:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
    <p>No Quiz is available please select the type of quiz you would like to take on the Quiz Selection page.</p>
    {% endif %}
 {% endif %}
        </div>
      </div>
    </div>
    <div id="copyright"> &copy; Copyright 2016 | Web Design & Software Application Development By <a target=_blank href="http://www.gilrael.com">Gil Rael</a></div>
  </div>
  <div id="footer"> </div>
</div>
</body>
</html>

redhat_sensei_quiz/templates/test.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<br xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Model Portfolio template</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link rel="stylesheet" href="/static/css/style.css" type="text/css" charset="utf-8" />
</head>
<br>
<br id="wrapper">
  <div id="header">
    <h1><span>RED HAT LINUX SENSEI</span></h1>
  </div>
  <div id="nav">
    <ul>
      <li class="first"><a href="#"><em>A</em>BOUT</a></li>
      <li><a href="#"><em>R</em>EGISTER</a></li>
      <li><a href="#"><em>L</em>OGIN</a></li>
    </ul>
  </div>
  <div id="body">
    <div id="content">
      <div class="i">
        <h1><strong>Welcome</strong> To Red Hat Linux Sensei</h1>
        <p>Red Hat Linux Sensei is an educational web application designed to test Red Hat Linux system administration skills.
        The application is designed and developed by Gil Rael using the python django web application framework.</p>
        </div>
      </div>
    </div>
      <div id="copyright"> &copy;         Copyright 2016 | Web Design And Application Development By Gil Rael <a href="http://gilrael.com/">Contact Gil Rael</a></div>
  </div>
  <div id="footer"> </div>
</div>
</body>
</html>